name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: hello1
        run: echo 'hello'
        
      - name: UnInstallService
        run: If (Get-Service ProductivityTools.Alibaba -ErrorAction SilentlyContinue) {UnInstall-Service -ExePath C:\Bin\ProductivityTools.AlibabaCloud.IpMonitor\ProductivityTools.AlibabaCloud.IpMonitor.exe}
        shell: powershell
        
      - name: Stop Service
        run: If (Get-Service PT.Alibaba -ErrorAction SilentlyContinue) {stop-service -name PT.Alibaba}
        shell: powershell
        
      - name: UnInstallServiceNetCore
        run: If (Get-Service PT.Alibaba -ErrorAction SilentlyContinue) {sc.exe delete PT.Alibaba}
        shell: powershell
        
      - name: checkout
        uses: actions/checkout@v4
        
      - name: build
        run: |
          echo 'starting bddduild'
          dotnet publish ProductivityTools.AlibabaCloud.sln -c Release
        shell: cmd
        
      - name: RemoveDirectory
        run: Remove-Item -Recurse -Force "C:\Bin\Services\ProductivityTools.AlibabaCloud.NetCoreService\" -ErrorAction SilentlyContinue
        shell: powershell
        
      - name: CopyFiles
        run: xcopy ".\ProductivityTools.AlibabaCloud.NetCoreService\bin\Release\net9.0\publish\" "C:\Bin\Services\ProductivityTools.AlibabaCloud.NetCoreService\" /O /X /E /H /K /Y /I
        shell: cmd
        
      - name: InstallService
        run: sc.exe create PT.Alibaba binpath="C:\Bin\Services\ProductivityTools.AlibabaCloud.NetCoreService\ProductivityTools.AlibabaCloud.NetCoreService.exe"
        shell: powershell
        
      - name: StartService
        run: Start-Service PT.Alibaba
        shell: powershell
        
      - name: byebye
        run: echo 'byebye'
